-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Launcher

-- bindd = SUPER, SPACE, Open application launcher with rofi, exec, ~/.config/rofi/launchers/drun.sh

-- bindd = SUPER, SPACE, Open Walker launcher, exec, walker

-- Terminal

hl.bind(
	"SUPER + RETURN",
	hl.dsp.exec_cmd("kitty --directory=$(bash ~/.config/hypr/scripts/terminal-open-cwd.sh)"),
	{ description = "Open terminal in current working directory" }
)

-- Browser

hl.bind("SUPER + B", hl.dsp.exec_cmd("chromium"), { description = "Open browser" })

-- Private browser

hl.bind(
	"SUPER + SHIFT + B",
	hl.dsp.exec_cmd("chromium --incognito"),
	{ description = "Open browser in incognito mode" }
)

-- File manager

hl.bind("SUPER + SHIFT + F", hl.dsp.exec_cmd("kitty -e yazi"), { description = "Open Yazi file manager" })

-- Editor

hl.bind("SUPER + SHIFT + N", hl.dsp.exec_cmd("kitty nvim"), { description = "Open VS Code" })

-- Resource monitor

hl.bind(
	"SUPER + CTRL + T",
	hl.dsp.exec_cmd("kitty --class floating_btop btop"),
	{ description = "Open Btop system monitor" }
)

-- Lock

hl.bind("SUPER + L", hl.dsp.exec_cmd("hyprlock"), { description = "Lock screen" })

-- Logout menu

hl.bind(
	"SUPER + CTRL + Q",
	hl.dsp.exec_cmd("wlogout -b 6 --protocol layer-shell"),
	{ description = "Open logout menu" }
)

-- wifi impala

hl.bind(
	"SUPER + CTRL + W",
	hl.dsp.exec_cmd("kitty --class floating_impala impala"),
	{ description = "Open Impala WiFi manager" }
)

-- bluetooth bluetui

hl.bind(
	"SUPER + CTRL + B",
	hl.dsp.exec_cmd("kitty --class floating_bluetui bluetui"),
	{ description = "Open Bluetui Bluetooth manager" }
)

-- swaync
-- Notifications

hl.bind("SUPER + SHIFT + COMMA", hl.dsp.exec_cmd("swaync-client -t"), { description = "Toggle notification center" })

hl.bind(
	"SUPER + CTRL + COMMA",
	hl.dsp.exec_cmd("swaync-client --close-latest"),
	{ description = "Dismiss latest notification" }
)

hl.bind(
	"SUPER + SHIFT + CTRL + COMMA",
	hl.dsp.exec_cmd("swaync-client -C && notify-send 'Notifications cleared'"),
	{ description = "Clear all notifications" }
)

-- Toggle DND

hl.bind(
	"SUPER + ALT + COMMA",
	hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/toggle-dnd.sh"),
	{ description = "Toggle do not disturb mode" }
)

-- gnome-calculator
hl.bind("XF86Calculator", hl.dsp.exec_cmd("gnome-calculator"), { description = "Open calculator" })
