# Navigate grouped windows
bindd = SUPER, PERIOD, Switch to next window in group, changegroupactive, f
bindd = SUPER, COMMA, Switch to previous window in group, changegroupactive, b

# Move into groups
bindd = SUPER ALT, LEFT, Move window into group on the left, moveintogroup, l
bindd = SUPER ALT, RIGHT, Move window into group on the right, moveintogroup, r
bindd = SUPER ALT, UP, Move window into group above, moveintogroup, u
bindd = SUPER ALT, DOWN, Move window into group below, moveintogroup, d

# Scroll grouped windows
bindd = SUPER ALT, mouse_down, Switch to next grouped window with mouse scroll, changegroupactive, f
bindd = SUPER ALT, mouse_up, Switch to previous grouped window with mouse scroll, changegroupactive, b
#
