-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Volume

-- bindel = , XF86AudioRaiseVolume, exec, pamixer -i 5

-- bindel = , XF86AudioLowerVolume, exec, pamixer -d 5

-- bindel = , XF86AudioMute, exec, pamixer -t

-- audio

hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("swayosd-client --output-volume +5"),
	{ locked = true, description = "Increase system volume" }
)

hl.bind(
	"ALT + XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("swayosd-client --output-volume +1"),
	{ locked = true, description = "Increase system volume (fine)" }
)

hl.bind(
	"ALT + XF86AudioLowerVolume",
	hl.dsp.exec_cmd("swayosd-client --output-volume -1"),
	{ locked = true, description = "Decrease system volume (fine)" }
)

hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("swayosd-client --output-volume -5"),
	{ locked = true, description = "Decrease system volume" }
)

hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"),
	{ locked = true, description = "Toggle audio mute" }
)

-- Mic

hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("pamixer --default-source -t"),
	{ locked = true, description = "Toggle microphone mute" }
)

-- Brightness
--
local function brightness(step)
	return string.format(
		[[
		sh -c '
			brightnessctl -e set "%s"

			current=$(brightnessctl g)
			max=$(brightnessctl m)

			progress=$(awk "BEGIN { print $current/$max }")
			percent=$(( current * 100 / max ))

			swayosd-client \
				--custom-icon display-brightness-symbolic \
				--custom-progress "$progress" \
				--custom-progress-text "$(printf "%%3d%%%%" "$percent")"
		'
	]],
		step
	)
end

hl.bind(
	"XF86MonBrightnessUp",
	hl.dsp.exec_cmd(brightness("+5%")),
	{ locked = true, description = "Increase screen brightness" }
)

hl.bind(
	"XF86MonBrightnessDown",
	hl.dsp.exec_cmd(brightness("5%-")),
	{ locked = true, description = "Decrease screen brightness" }
)

hl.bind(
	"ALT + XF86MonBrightnessUp",
	hl.dsp.exec_cmd(brightness("+1%")),
	{ locked = true, description = "Increase screen brightness (fine)" }
)

hl.bind(
	"ALT + XF86MonBrightnessDown",
	hl.dsp.exec_cmd(brightness("1%-")),
	{ locked = true, description = "Decrease screen brightness (fine)" }
)

-- Media

hl.bind(
	"XF86AudioPlay",
	hl.dsp.exec_cmd("playerctl play-pause"),
	{ locked = true, description = "Toggle media playback" }
)

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true, description = "Play next media track" })

hl.bind(
	"XF86AudioPrev",
	hl.dsp.exec_cmd("playerctl previous"),
	{ locked = true, description = "Play previous media track" }
)
