-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true, description = "Drag floating window" })

hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true, description = "Resize floating window" })
