-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Toggle scratchpads

hl.bind("SUPER + S", hl.dsp.workspace.toggle_special("default-scratch"), { description = "Toggle default scratchpad" })

hl.bind("ALT + Z", hl.dsp.workspace.toggle_special("term"), { description = "Toggle terminal scratchpad" })

hl.bind("ALT + X", hl.dsp.workspace.toggle_special("music"), { description = "Toggle music scratchpad" })

hl.bind("ALT + C", hl.dsp.workspace.toggle_special("misc"), { description = "Toggle miscellaneous scratchpad" })

-- Send windows to scratchpads

hl.bind(
	"SUPER + ALT + S",
	hl.dsp.window.move({ workspace = "special:default-scratch" }, { follow = false }),
	{ description = "Send window to default scratchpad" }
)

hl.bind(
	"ALT + SHIFT + Z",
	hl.dsp.window.move({ workspace = "special:term" }, { follow = false }),
	{ description = "Send window to terminal scratchpad" }
)

hl.bind(
	"ALT + SHIFT + X",
	hl.dsp.window.move({ workspace = "special:music" }, { follow = false }),
	{ description = "Send window to music scratchpad" }
)

hl.bind(
	"ALT + SHIFT + C",
	hl.dsp.window.move({ workspace = "special:misc" }, { follow = false }),
	{ description = "Send window to miscellaneous scratchpad" }
)
