-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Screenshot

hl.bind(
	"Print",
	hl.dsp.exec_cmd("grimblast copy area && notify-send 'Shot captured and copied'"),
	{ description = "Capture selected screenshot and copy to clipboard" }
)

hl.bind(
	"SHIFT + Print",
	hl.dsp.exec_cmd(
		"grimblast --freeze copysave area ~/Pictures/screenshots/$(date +%Y-%m-%d_%H-%M-%S).png && notify-send 'Shot captured and saved'"
	),
	{ description = "Capture selected screenshot and save to file" }
)

-- Screen record

hl.bind("ALT + PRINT", hl.dsp.exec_cmd("wf-recorder"), { description = "Start screen recording" })

-- Color picker

hl.bind("SUPER + PRINT", hl.dsp.exec_cmd("hyprpicker -a"), { description = "Pick color and copy hex code" })

-- Notifications

hl.bind("SUPER + COMMA", hl.dsp.exec_cmd("swaync-client -t"), { description = "Toggle notification center" })

hl.bind(
	"SUPER + SHIFT + COMMA",
	hl.dsp.exec_cmd("swaync-client --close-latest"),
	{ description = "Dismiss latest notification" }
)

hl.bind(
	"SUPER + CTRL + COMMA",
	hl.dsp.exec_cmd("swaync-client -C && notify-send 'Notifications cleared'"),
	{ description = "Clear all notifications" }
)

-- Toggle DND

hl.bind(
	"SUPER + ALT + COMMA",
	hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/toggle-dnd.sh"),
	{ description = "Toggle do not disturb mode" }
)

-- Reload config

hl.bind("SUPER + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"), { description = "Reload Hyprland configuration" })

-- Exit Hyprland

hl.bind("SUPER + SHIFT + Q", hl.dsp.exit(), { description = "Exit Hyprland session" })

-- OBS monitor focus

hl.bind("SUPER + F9", hl.dsp.focus({ workspace = "name:OBS" }), { description = "Focus OBS monitor" })

hl.bind("SUPER + F8", hl.dsp.focus({ workspace = "name:eDP-2" }), { description = "Focus laptop display" })

-- refresh waybar

hl.bind("SUPER + SHIFT + SPACE", hl.dsp.exec_cmd("sh -c 'pkill waybar || waybar'"), { description = "Restart Waybar" })

--## walker menus

-- Main launcher

hl.bind("SUPER + SPACE", hl.dsp.exec_cmd("walker -t pywal"), { description = "Open Walker launcher" })

-- wallpaper change with awww

hl.bind("SUPER + W", hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/wallpaper.sh"), { description = "Change wallpaper" })

hl.bind(
	"SUPER + SHIFT + W",
	hl.dsp.exec_cmd("walker -t pywal --provider menus:wallpaper"),
	{ description = "Open wallpaper selection menu" }
)

-- Clipboard

hl.bind(
	"SUPER + V",
	hl.dsp.exec_cmd("walker -t pywal --provider clipboard"),
	{ description = "Open clipboard history" }
)

-- Symbols / Emoji

hl.bind(
	"SUPER + E",
	hl.dsp.exec_cmd("walker -t pywal --provider symbols"),
	{ description = "Open emoji and symbols picker" }
)

-- keybindings menus

hl.bind(
	"SUPER + K",
	hl.dsp.exec_cmd("walker -t pywal --provider menus:keybinds"),
	{ description = "Open keybindings help menu" }
)

-- toggle idle

hl.bind(
	"CTRL + SHIFT + I",
	hl.dsp.exec_cmd("bash ~/.config/hypr/scripts/toggle-idle.sh"),
	{ description = "Toggle idle mode" }
)
