-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Close

hl.bind("SUPER + Q", hl.dsp.window.close(), { description = "Close active window" })

-- Fullscreen and full width

hl.bind(
	"SUPER + F",
	hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }),
	{ description = "Full screen" }
)

hl.bind(
	"SUPER + CTRL + F",
	hl.dsp.window.fullscreen_state({ internal = 0, client = 2, action = "toggle" }),
	{ description = "Tiled full screen" }
)

hl.bind(
	"SUPER + ALT + F",
	hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }),
	{ description = "Full width" }
)

-- Floating

hl.bind("SUPER + T", hl.dsp.window.float(), { description = "Toggle floating mode for active window" })

-- Pseudo tile

hl.bind("SUPER + P", hl.dsp.window.pseudo(), { description = "Toggle pseudo tiling for active window" })

-- Split orientation

hl.bind("SUPER + J", hl.dsp.layout("togglesplit"), { description = "Toggle split orientation" })

-- Focus

hl.bind("SUPER + LEFT", hl.dsp.focus({ direction = "left" }), { description = "Focus window to the left" })

hl.bind("SUPER + RIGHT", hl.dsp.focus({ direction = "right" }), { description = "Focus window to the right" })

hl.bind("SUPER + UP", hl.dsp.focus({ direction = "up" }), { description = "Focus window above" })

hl.bind("SUPER + DOWN", hl.dsp.focus({ direction = "down" }), { description = "Focus window below" })

-- Swap windows

hl.bind(
	"SUPER + SHIFT + LEFT",
	hl.dsp.window.swap({ direction = "left" }),
	{ description = "Swap active window with left window" }
)

hl.bind(
	"SUPER + SHIFT + RIGHT",
	hl.dsp.window.swap({ direction = "right" }),
	{ description = "Swap active window with right window" }
)

hl.bind(
	"SUPER + SHIFT + UP",
	hl.dsp.window.swap({ direction = "up" }),
	{ description = "Swap active window with upper window" }
)

hl.bind(
	"SUPER + SHIFT + DOWN",
	hl.dsp.window.swap({ direction = "down" }),
	{ description = "Swap active window with lower window" }
)

-- Resize

-- TODO: manual review (unknown dispatcher: Shrink active window horizontally)
-- hl.bind("SUPER + minus", hl.dsp.Shrink active window horizontally("resizeactive", "-60 0"))

hl.bind(
	"SUPER + minus",
	hl.dsp.window.resize({ x = -60, y = 0, relative = true }),
	{ description = "Shrink active window horizontally" }
)

-- TODO: manual review (unknown dispatcher: Expand active window horizontally)
-- hl.bind("SUPER + equal", hl.dsp.Expand active window horizontally("resizeactive", "60 0"))

hl.bind(
	"SUPER + equal",
	hl.dsp.window.resize({ x = 60, y = 0, relative = true }),
	{ description = "Expand active window horizontally" }
)

-- TODO: manual review (unknown dispatcher: Shrink active window vertically)
-- hl.bind("SUPER + SHIFT + minus", hl.dsp.Shrink active window vertically("resizeactive", "0 -60"))

hl.bind(
	"SUPER + SHIFT + minus",
	hl.dsp.window.resize({ x = 0, y = -60, relative = true }),
	{ description = "Shrink active window vertically" }
)

-- TODO: manual review (unknown dispatcher: Expand active window vertically)
-- hl.bind("SUPER + SHIFT + equal", hl.dsp.Expand active window vertically("resizeactive", "0 60"))

hl.bind(
	"SUPER + SHIFT + equal",
	hl.dsp.window.resize({ x = 0, y = 60, relative = true }),
	{ description = "Expand active window vertically" }
)

-- Alt-tab

hl.bind("ALT + TAB", hl.dsp.window.cycle_next(), { description = "Cycle to next window" })

-- TODO: manual review (unknown dispatcher: Bring active window to top)
-- hl.bind("ALT + TAB", hl.dsp.Bring active window to top("bringactivetotop"))
hl.bind("ALT + TAB", hl.dsp.window.bring_to_top(), { description = "Bring active window to top" })

hl.bind("ALT + SHIFT + TAB", hl.dsp.window.cycle_next({ next = false }), { description = "Cycle to previous window" })

-- TODO: manual review (unknown dispatcher: Bring active window to top)
-- hl.bind("ALT + SHIFT + TAB", hl.dsp.Bring active window to top("bringactivetotop"))
hl.bind("ALT + SHIFT + TAB", hl.dsp.window.bring_to_top(), { description = "Bring active window to top" })

-- Toggle groups

hl.bind("SUPER + G", hl.dsp.group.toggle(), { description = "Toggle grouped windows mode" })

hl.bind(
	"SUPER + ALT + G",
	hl.dsp.window.move({ out_of_group = true }),
	{ description = "Move active window out of current group" }
)
