# Close
bindd = SUPER, Q, Close active window, killactive

# Fullscreen and full width
bindd = SUPER, F, Toggle fullscreen mode, fullscreen, 0
bindd = SUPER ALT, F, Full width, fullscreen, 1

# Floating
bindd = SUPER, T, Toggle floating mode for active window, togglefloating

# Pseudo tile
bindd = SUPER, P, Toggle pseudo tiling for active window, pseudo

# Split orientation
bindd = SUPER, J, Toggle split orientation, togglesplit

# Focus
bindd = SUPER, LEFT, Focus window on the left, movefocus, l
bindd = SUPER, RIGHT, Focus window on the right, movefocus, r
bindd = SUPER, UP, Focus window above, movefocus, u
bindd = SUPER, DOWN, Focus window below, movefocus, d

# Swap windows
bindd = SUPER SHIFT, LEFT, Swap window with left window, swapwindow, l
bindd = SUPER SHIFT, RIGHT, Swap window with right window, swapwindow, r
bindd = SUPER SHIFT, UP, Swap window with upper window, swapwindow, u
bindd = SUPER SHIFT, DOWN, Swap window with lower window, swapwindow, d

# Resize
bindd = SUPER, minus, Shrink active window horizontally, resizeactive, -60 0
bindd = SUPER, equal, Expand active window horizontally, resizeactive, 60 0

bindd = SUPER SHIFT, minus, Shrink active window vertically, resizeactive, 0 -60
bindd = SUPER SHIFT, equal, Expand active window vertically, resizeactive, 0 60

# Alt-tab
bindd = ALT, TAB, Switch to next window, cyclenext
bindd = ALT, TAB, Bring active window to top, bringactivetotop

bindd = ALT SHIFT, TAB, Switch to previous window, cyclenext, prev
bindd = ALT SHIFT, TAB, Bring active window to top, bringactivetotop

# Toggle groups
bindd = SUPER, G, Toggle grouped windows, togglegroup
bindd = SUPER ALT, G, Remove window from group, moveoutofgroup
