-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Workspaces
--
for workspace = 1, 10 do
	local key = "code:" .. tostring(workspace + 9)

	hl.bind("SUPER + " .. key, hl.dsp.focus({ workspace = tostring(workspace) }))

	hl.bind("SUPER + SHIFT + " .. key, hl.dsp.window.move({ workspace = tostring(workspace) }))

	hl.bind(
		"SUPER + SHIFT + ALT + " .. key,
		hl.dsp.window.move({
			workspace = tostring(workspace),
			follow = false,
		})
	)
end

-- hl.bind("SUPER" .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
--
-- hl.bind("SUPER" .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
--
-- hl.bind("SUPER" .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
--
-- hl.bind("SUPER" .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
--
-- hl.bind("SUPER" .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
--
-- hl.bind("SUPER" .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
--
-- hl.bind("SUPER" .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
--
-- hl.bind("SUPER" .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
--
-- hl.bind("SUPER" .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))
--
-- hl.bind("SUPER" .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))
--
-- -- Move windows
--
-- hl.bind("SUPER + SHIFT" .. " + " .. 1, hl.dsp.window.move(1))
--
-- hl.bind("SUPER + SHIFT" .. " + " .. 2, hl.dsp.window.move(2))
--
-- hl.bind("SUPER + SHIFT" .. " + " .. 3, hl.dsp.window.move(3))
--
-- hl.bind("SUPER + SHIFT" .. " + " .. 4, hl.dsp.window.move(4))
--
-- hl.bind("SUPER + SHIFT" .. " + " .. 5, hl.dsp.window.move(5))
--
-- hl.bind("SUPER + SHIFT" .. " + " .. 6, hl.dsp.window.move(6))
--
-- hl.bind("SUPER + SHIFT" .. " + " .. 7, hl.dsp.window.move(7))
--
-- hl.bind("SUPER + SHIFT" .. " + " .. 8, hl.dsp.window.move(8))
--
-- hl.bind("SUPER + SHIFT" .. " + " .. 9, hl.dsp.window.move(9))
--
-- hl.bind("SUPER + SHIFT" .. " + " .. 0, hl.dsp.window.move(10))
--
-- -- Silent move
--
-- hl.bind("SUPER + SHIFT + ALT" .. " + " .. 1, hl.dsp.window.move(1, { follow = false }))
--
-- hl.bind("SUPER + SHIFT + ALT" .. " + " .. 2, hl.dsp.window.move(2, { follow = false }))
--
-- hl.bind("SUPER + SHIFT + ALT" .. " + " .. 3, hl.dsp.window.move(3, { follow = false }))
--
-- hl.bind("SUPER + SHIFT + ALT" .. " + " .. 4, hl.dsp.window.move(4, { follow = false }))
--
-- hl.bind("SUPER + SHIFT + ALT" .. " + " .. 5, hl.dsp.window.move(5, { follow = false }))

-- Cycle workspaces

hl.bind("SUPER" .. " + " .. "TAB", hl.dsp.focus({ workspace = "e+1" }))

hl.bind("SUPER + SHIFT" .. " + " .. "TAB", hl.dsp.focus({ workspace = "e-1" }))

-- Previous workspace

hl.bind("SUPER + CTRL" .. " + " .. "TAB", hl.dsp.focus({ workspace = "previous" }))

-- Move workspace between monitors

-- TODO: manual review (unknown dispatcher: Move current workspace to left monitor)
-- hl.bind("SUPER + SHIFT + ALT + LEFT", hl.dsp.Move current workspace to left monitor("movecurrentworkspacetomonitor", "l"))

-- TODO: manual review (unknown dispatcher: Move current workspace to right monitor)
-- hl.bind("SUPER + SHIFT + ALT + RIGHT", hl.dsp.Move current workspace to right monitor("movecurrentworkspacetomonitor", "r"))
