# Notifications
exec-once = swaync

# Wallpaper
exec-once = awww-daemon

# Idle daemon
exec-once = hypridle

# Status bar
exec-once = waybar

# Volume OSD
exec-once = swayosd-server

# Polkit agent
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Clipboard manager (optional later)
# exec-once = wl-paste --type text --watch cliphist store
# exec-once = wl-paste --type image --watch cliphist store
#
# walker and elephant
exec-once = elephant
exec-once = env GSK_RENDERER=cairo walker --gapplication-service

# Cursor
exec-once = hyprctl setcursor Bibata-Modern-Ice 22

# Environment propagation
exec-once = dbus-update-activation-environment --systemd --all

# hyprtimed
exec-once = hyprtimed
