-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Cursor

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

-- Wayland

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- GTK

hl.env("GDK_BACKEND", "wayland,x11,*")

-- Qt

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-- Mozilla

hl.env("MOZ_ENABLE_WAYLAND", 1)

-- Electron

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")

hl.env("OZONE_PLATFORM", "wayland")

-- XCompose

hl.env("XCOMPOSEFILE", "~/.XCompose")

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

hl.config({
    ecosystem = {
        no_update_news = true,
    },
})

hl.env("LIBVA_DRIVER_NAME", "nvidia")

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.env("NVD_BACKEND", "direct")

hl.env("GBM_BACKEND", "nvidia-drm")

-- hybrid gpu

-- env = AQ_DRM_DEVICES,/dev/dri/by-path/pci-0000:00:02.0-card
