# =========================
# Environment
# =========================
source = ~/.config/hypr/envs.conf

# =========================
# Monitor configuration
# =========================
source = ~/.config/hypr/monitors.conf

# =========================
# Look and feel
# =========================
source = ~/.config/hypr/looknfeel.conf

# =========================
# Window rules
# =========================
source = ~/.config/hypr/windowrules.conf

# =========================
# Keybindings
# =========================
source = ~/.config/hypr/bindings.conf

# =========================
# Startup applications
# =========================
source = ~/.config/hypr/autostart.conf

# =========================
# Layer rules
# =========================
source = ~/.config/hypr/layerrules.conf

# =========================
# Input
# =========================
input {
    kb_layout = us

    follow_mouse = 1

    touchpad {
        natural_scroll = true
        tap-to-click = true
        disable_while_typing = true
    }

    sensitivity = 0
}

# =========================
# Decorations
# =========================

decoration {
    blur {
        enabled = true
    }
}

# =========================
# Gestures
# =========================
 
# Horizontal 3-finger swipe for workspace navigation
gesture = 3, horizontal, workspace, m-1 # or m+1 depending on preference


# =========================
# XWayland
# =========================
xwayland {
    force_zero_scaling = true
}

# =========================
# Device-specific overrides
# =========================
# device {
#     name = epic-mouse-v1
#     sensitivity = -0.5
# }


# hyprlock with suspend
# bindl=,switch:on:Lid Switch, exec, hyprlock
bindl=,switch:on:Lid Switch,exec,pidof hyprlock || hyprlock






