-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- =========================

-- Environment

-- =========================

-- source = ~/.config/hypr/envs.conf -> requires manual conversion
require("envs")
-- TODO: convert ~/.config/hypr/envs.conf to .lua and use require()

-- =========================

-- Monitor configuration

-- =========================

-- source = ~/.config/hypr/monitors.conf -> requires manual conversion
require("monitors")
-- TODO: convert ~/.config/hypr/monitors.conf to .lua and use require()

-- =========================

-- Look and feel

-- =========================

-- source = ~/.config/hypr/looknfeel.conf -> requires manual conversion
require("looknfeel")
-- TODO: convert ~/.config/hypr/looknfeel.conf to .lua and use require()

-- =========================

-- Window rules

-- =========================

-- source = ~/.config/hypr/windowrules.conf -> requires manual conversion
require("windowrules")
-- TODO: convert ~/.config/hypr/windowrules.conf to .lua and use require()

-- =========================

-- Keybindings

-- =========================

-- source = ~/.config/hypr/bindings.conf -> requires manual conversion
require("bindings")
-- TODO: convert ~/.config/hypr/bindings.conf to .lua and use require()

-- =========================

-- Startup applications

-- =========================

-- source = ~/.config/hypr/autostart.conf -> requires manual conversion
require("autostart")
-- TODO: convert ~/.config/hypr/autostart.conf to .lua and use require()

-- =========================

-- Layer rules

-- =========================

-- source = ~/.config/hypr/layerrules.conf -> requires manual conversion
require("layerrules")
-- TODO: convert ~/.config/hypr/layerrules.conf to .lua and use require()

-- =========================

-- Input

-- =========================

-- hl.config({
--     input = {
--         kb_layout = "us",
--         follow_mouse = 1,
--         touchpad = {
--             natural_scroll = true,
--             tap-to-click = true,
--             disable_while_typing = true,
--         },
--         sensitivity = 0,
--     },
-- })

hl.config({
	input = {
		kb_layout = "us",
		follow_mouse = 1,
		touchpad = {
			natural_scroll = true,
			tap_to_click = true,
			disable_while_typing = true,
		},
		sensitivity = 0,
	},
})

-- =========================

-- Decorations

-- =========================

hl.config({
	decoration = {
		blur = {
			enabled = true,
			size = 3,
			xray = false,
			special = true,
			popups = true,
			passes = 3,
		},
	},
})

-- =========================

-- Gestures

-- =========================

-- Horizontal 3-finger swipe for workspace navigation

-- TODO: manual review: gesture = 3, "horizontal", "workspace", "m-1"

-- or m+1 depending on preference

-- =========================

-- XWayland

-- =========================

hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
})

-- =========================

-- Device-specific overrides

-- =========================

-- device {

--     name = epic-mouse-v1

--     sensitivity = -0.5

-- }

-- hyprlock with suspend

-- bindl=,switch:on:Lid Switch, exec, hyprlock

hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("pidof hyprlock || hyprlock"), { locked = true })

require("input")

-- debug({
-- 	disable_logs = true,
-- })
