-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Control your input devices

-- See https://wiki.hypr.land/Configuring/Variables/#input

hl.config({
	input = {
		-- Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
		-- kb_layout = us,dk,eu
		kb_layout = "us",
		kb_options = "fkeys:basic_13-24",
		-- ,grp:alts_toggle
		-- Change speed of keyboard repeat
		repeat_rate = 40,
		repeat_delay = 600,
		-- Start with numlock on by default
		numlock_by_default = true,
		-- Increase sensitivity for mouse/trackpad (default: 0)
		sensitivity = 0.1,
		touchpad = {
			-- Use natural (inverse) scrolling
			natural_scroll = true,
			-- Use two-finger clicks for right-click instead of lower-right corner
			clickfinger_behavior = true,
			-- Control the speed of your scrolling
			-- scroll_factor = 0.4
			-- Left-click-and-drag with three fingers
			-- drag_3fg = 1
			--   touchpad {
			--     # mouse_ref/ocus = false
			-- }
			disable_while_typing = true,
		},
	},
})

hl.config({
	misc = {
		key_press_enables_dpms = true,
		-- key press will trigger wake
		mouse_move_enables_dpms = true,
		-- mouse move will trigger wake
	},
})

-- Scroll nicely in the terminal

hl.window_rule({
	name = "scroll_touchpad 1.5",
	match = {
		class = "(Alacritty|kitty)",
	},
	-- TODO: review rule: "match:class (Alacritty|kitty)"
})

-- Enable touchpad gestures for changing workspaces

-- See https://wiki.hyprland.org/Configuring/Gestures/

-- TODO: manual review: gesture = 3, "horizontal", "workspace"
