-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.layer_rule({
	match = {
		namespace = "swaync-control-center",
	},
	blur = on,
})

hl.layer_rule({
	match = {
		namespace = "swaync-control-center",
	},
	ignore_alpha = 0.4,
	dim_around = true,
})

hl.layer_rule({
	match = {
		namespace = "swaync-notification-window",
	},
	blur = on,
})

hl.layer_rule({
	match = {
		namespace = "swaync-notification-window",
	},
	ignore_alpha = 0.4,
})

hl.layer_rule({
	match = {
		namespace = "logout_dialog",
	},
	blur = true,
	dim_around = true,
})

hl.layer_rule({
	match = {
		namespace = "logout_dialog",
	},
	ignore_alpha = 0.2,
})

-- Waybar main panel

hl.layer_rule({
	match = {
		namespace = "^waybar$",
	},
	blur = true,
	ignore_alpha = 0.2,
	xray = true,
	dim_around = false,
})

-- hl.layer_rule({
-- 	match = {
-- 		namespace = "^waybar$",
-- 	},
-- 	ignore_alpha = 0.8,
-- })

hl.layer_rule({
	match = {
		namespace = "^waybar-tooltip$",
	},
	blur = on,
	ignore_alpha = 0.2,
	xray = true,
})

-- hl.layer_rule({
-- 	match = {
-- 		namespace = "^waybar-tooltip$",
-- 	},
-- 	ignore_alpha = 0.2,
-- })

--

--

-- layerrule = blur, logout_dialog

-- layerrule = ignorealpha 0.3, logout_dialog

--

--

-- # layerrule {

-- #     name = wlogout-blur

-- #     blur = on

-- #     ignore_alpha = 0

-- #     match:namespace = logout_dialog

-- # }

-- #

-- # layerrule = blur, swaync-control-center

--

--

-- layerrule = blur, swaync-control-center

-- layerrule = ignorealpha 0.4, swaync-control-center

--

-- layerrule = blur, swaync-notification-window

-- layerrule = ignorealpha 0.4, swaync-notification-window

--

-- # layerrule {

-- #   name = layerrule-1

-- #   blur = on

-- #   match:namespace = swaync-control-center

-- # }

-- #    # Layer 5629110a0dd0: xywh: 0 38 1920 1042, namespace: swaync-control-center, pid: 62280

-- #

-- # # layerrule = blur, swaync-notification-window

-- #

-- # layerrule {

-- #   name = layerrule-1

-- #   blur = on

-- #   match:namespace = swaync-notification-window

-- # }

-- #

-- # # layerrule = ignorealpha 0.4, swaync-control-center

-- #

-- # layerrule {

-- #   name = layerrule-1

-- #   ignore_alpha = 0.4

-- #   match:namespace = swaync-control-center

-- # }

-- #

-- # # layerrule = ignorealpha 0.4, swaync-notification-window

-- #

-- # layerrule {

-- #   name = layerrule-1

-- #   ignore_alpha = 0.4

-- #   match:namespace = swaync-notification-window

-- # }

-- #
