-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Change the default Omarchy look'n'feel

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/

-- Variables

-- set no borders

local active_border_color = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 }
local inactive_border_color = "rgba(595959aa)"

-- https://wiki.hyprland.org/Configuring/Variables/#general

-- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
-- Set to true enable resizing windows by clicking and dragging on borders and gaps
-- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on

hl.config({
	general = {
		gaps_in = 3,
		gaps_out = 6,
		border_size = 0,
		col = {
			active_border = active_border_color,
			inactive_border = inactive_border_color,
		},
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
	decoration = {
		rounding = 10,
		shadow = {
			enabled = true,
			range = 2,
			render_power = 3,
			color = "rgba(1a1a1aee)",
		},
		-- https://wiki.hyprland.org/Configuring/Variables/#blur
		blur = {
			enabled = true,
			size = 2,
			passes = 2,
			special = true,
			brightness = 0.60,
			contrast = 0.75,
		},
	},
})

-- https://wiki.hypr.land/Configuring/Variables/#group

hl.config({
	group = {
		col = {
			border_active = active_border_color,
			border_inactive = inactive_border_color,
		},
		groupbar = {
			font_size = 12,
			font_family = "monospace",
			font_weight_active = "ultraheavy",
			font_weight_inactive = "normal",
			indicator_height = 0,
			indicator_gap = 5,
			height = 22,
			gaps_in = 5,
			gaps_out = 0,
			text_color = "rgb(ffffff)",
			text_color_inactive = "rgba(ffffff90)",
			col = {
				active = "rgba(00000040)",
				inactive = "rgba(00000020)",
			},
			gradients = true,
			gradient_rounding = 0,
			gradient_round_only_edges = false,
		},
	},
})

-- for presentation notest

-- was for transperant slide to not be visible in presentation
-- hl.window_rule({
-- 	name = "match_title____slide",
-- 	match = {
-- 		class = "opacity 0.50 override 0.5 override",
-- 	},
-- 	-- TODO: review rule: "match:title ^(「slide」- Chromium)$"
-- })

-- https://wiki.hyprland.org/Configuring/Variables/#animations

hl.config({
	animations = {
		enabled = true,
	},
})

-- Default animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1.0 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 3.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = false })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 3, bezier = "easeOutQuint", style = "slidevert" })

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
	dwindle = {
		-- pseudotile removed in 0.55
		-- pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
		preserve_split = true,
		-- You probably want this
		force_split = 2,
		-- Always split on the right
	},
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
	master = {
		new_status = "master",
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		focus_on_activate = true,
		anr_missed_pings = 3,
		-- removed from hyprland
		-- ew_window_takes_over_fullscreen = 1
		on_focus_under_fullscreen = 1,
	},
})

-- allow workspace back and forth  (chanaged)

hl.config({
	binds = {
		workspace_back_and_forth = 1,
		movefocus_cycles_fullscreen = true,
		hide_special_on_workspace_change = true,
	},
})

-- https://wiki.hypr.land/Configuring/Variables/#cursor

hl.config({
	cursor = {
		hide_on_key_press = true,
		-- added this
		inactive_timeout = 1,
	},
})

-- Style Gum confirm to match terminal theme

hl.env("GUM_CONFIRM_PROMPT_FOREGROUND", 6)

-- Cyan

hl.env("GUM_CONFIRM_SELECTED_FOREGROUND", 0)

-- Black

hl.env("GUM_CONFIRM_SELECTED_BACKGROUND", 2)

-- Green

hl.env("GUM_CONFIRM_UNSELECTED_FOREGROUND", 0)

-- Black

hl.env("GUM_CONFIRM_UNSELECTED_BACKGROUND", 8)

-- Dark grey
