-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
	screencopy = {
		allow_token_by_default = true,
	},
})
-- NOTE: Section 'screencopy' may be a plugin or custom section; verify the output
