# Toggle scratchpads
bindd = SUPER, S, Toggle default scratchpad workspace, togglespecialworkspace, default-scratch
bindd = ALT, Z, Toggle terminal scratchpad workspace, togglespecialworkspace, term
bindd = ALT, X, Toggle music scratchpad workspace, togglespecialworkspace, music
bindd = ALT, C, Toggle miscellaneous scratchpad workspace, togglespecialworkspace, misc

# Send windows to scratchpads
bindd = SUPER ALT, S, Send window to default scratchpad workspace, movetoworkspacesilent, special:default-scratch
bindd = ALT SHIFT, Z, Send window to terminal scratchpad workspace, movetoworkspacesilent, special:term
bindd = ALT SHIFT, X, Send window to music scratchpad workspace, movetoworkspacesilent, special:music
bindd = ALT SHIFT, C, Send window to miscellaneous scratchpad workspace, movetoworkspacesilent, special:misc
