# Screenshot
bindd = , Print, Capture screenshot and copy to clipboard, exec, grimblast copy area && notify-send "Shot" "Captured and copied"
bindd = SHIFT, Print, Capture area screenshot and save to file, exec, grimblast --freeze copysave area ~/Pictures/screenshots/$(date +%Y-%m-%d_%H-%M-%S).png && notify-send "Shot" "Captured and saved"

# Screen record
bindd = ALT, PRINT, Start screen recording with wf-recorder, exec, wf-recorder

# Color picker
bindd = SUPER, PRINT, Pick and copy screen color, exec, hyprpicker -a

# Notifications
bindd = SUPER, COMMA, Toggle notification center, exec, swaync-client -t
bindd = SUPER SHIFT, COMMA, Close latest notification, exec, swaync-client --close-latest
bindd = SUPER CTRL, COMMA, Clear all notifications, exec, swaync-client -C && notify-send "Notifications cleared"

# Toggle DND
bindd = SUPER ALT, COMMA, Toggle Do Not Disturb mode, exec, sh -c 'STATE=$(swaync-client -d); [ "$STATE" = "true" ] && notify-send -u critical "DND Enabled" || notify-send "DND Disabled"'

# Reload config
bindd = SUPER SHIFT, R, Reload Hyprland config, exec, hyprctl reload

# Exit Hyprland
bindd = SUPER SHIFT, Q, Exit Hyprland session, exit

# OBS monitor focus
bindd = SUPER, F9, Focus OBS monitor, focusmonitor, OBS
bindd = SUPER, F8, Focus laptop display monitor, focusmonitor, eDP-2
#


# refresh waybar
bindd = SUPER SHIFT, SPACE, Toggle top bar, exec, sh -c 'pkill waybar || waybar'

### walker menus
#
# Main launcher
bindd = SUPER, SPACE, open app launcher, exec, walker -t pywal

# wallpaper change with awww
bindd = SUPER, W, change wallpaper randomly, exec, ~/.config/hypr/scripts/wallpaper.sh
bindd = SUPER SHIFT, W, open wallpaper picker, exec, walker -t pywal --provider menus:wallpaper

# Clipboard
bindd = SUPER, V, open clipboard, exec, walker -t pywal --provider clipboard

# Symbols / Emoji
bindd = SUPER, E, open emoji picker, exec, walker -t pywal --provider symbols

# keybindings menus
bindd = SUPER, K,  show all keybinds, exec, walker -t pywal --provider menus:keybinds

# toggle idle
bind = CTRL SHIFT, I, exec, ~/.config/hypr/scripts/toggle-idle.sh


# calculator
bindd = , XF86Calculator, Calculator, exec, gnome-calculator
