-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Browser tags and styling.
hl.window(
	"((google-)?[cC]hrom(e|ium)|[bB]rave-browser|[mM]icrosoft-edge|Vivaldi-stable|helium)",
	{ tag = "+chromium-based-browser" }
)
hl.window("([fF]irefox|zen|librewolf)", { tag = "+firefox-based-browser" })
hl.window({ tag = "chromium-based-browser" }, { tag = "-default-opacity", tile = true, opacity = "1.0 0.97" })
hl.window({ tag = "firefox-based-browser" }, { tag = "-default-opacity", opacity = "1.0 0.97" })

-- Video apps: remove chromium browser tag so they don't get opacity applied.
hl.window("(chrome-youtube.com__-Default|chrome-app.zoom.us__wc_home-Default)", { tag = "-chromium-based-browser" })
hl.window("(chrome-youtube.com__-Default|chrome-app.zoom.us__wc_home-Default)", { tag = "-default-opacity" })

-- Hide screen sharing notification windows.
hl.window({ title = ".*is sharing.*" }, { workspace = "special silent" })

--

--

-- # Browser types

-- match:class ((google-)?(chrom(e|ium)|Chrom(e|ium))|(brave-browser|Brave-browser)|(microsoft-edge|Microsoft-edge)|Vivaldi-stable|helium)

-- match:class (firefox|Firefox|zen|librewolf)

-- windowrule = tag -default-opacity, match:tag chromium-based-browser

-- windowrule = tag -default-opacity, match:tag firefox-based-browser

--

-- # Video apps: remove chromium browser tag so they don't get opacity applied

-- windowrule = tag -chromium-based-browser, match:class (chrome-youtube.com__-Default|chrome-app.zoom.us__wc_home-Default)

-- windowrule = tag -default-opacity, match:class (chrome-youtube.com__-Default|chrome-app.zoom.us__wc_home-Default)

--

-- # Force chromium-based browsers into a tile to deal with --app bug

-- windowrule = tile on, match:tag chromium-based-browser

--

-- # Only a subtle opacity change, but not for video sites

-- windowrule = opacity 1.0 0.97, match:tag chromium-based-browser

-- windowrule = opacity 1.0 0.97, match:tag firefox-based-browser

--

-- # Hide the screen-sharing notification bar (the "Hide" button on it is broken on Wayland)

-- windowrule = workspace special silent, match:title .*is sharing.*
