-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Define terminal tag to style them uniformly.
hl.window("(Alacritty|kitty|com.mitchellh.ghostty|foot)", { tag = "+terminal" })
hl.window({ tag = "terminal" }, { tag = "-default-opacity", opacity = "0.97 0.9" })
