-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Notifications


-- Wallpaper


-- Idle daemon


-- Status bar


-- Volume OSD


-- Polkit agent


-- Clipboard manager (optional later)

-- exec-once = wl-paste --type text --watch cliphist store

-- exec-once = wl-paste --type image --watch cliphist store

--

-- walker and elephant



-- Cursor


-- Environment propagation


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("swaync")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swayosd-server")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("elephant")
    hl.exec_cmd("env GSK_RENDERER=cairo walker --gapplication-service")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 22")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
end)
