-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- bindings.lua

require("binds.apps")
require("binds.windows")
require("binds.workspaces")
require("binds.media")
require("binds.scratchpads")
require("binds.groups")
require("binds.utilities")
require("binds.mouse")
