-- Generated by hyprconf2lua v1.1.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Navigate grouped windows

hl.bind("SUPER + PERIOD", hl.dsp.group.next(), { description = "Focus next window in group" })

hl.bind("SUPER + COMMA", hl.dsp.group.next({ forward = false }), { description = "Focus previous window in group" })

-- Move into groups

hl.bind("SUPER + ALT + LEFT", hl.dsp.window.move({ into_group = "l" }), { description = "Move window left in group" })

hl.bind("SUPER + ALT + RIGHT", hl.dsp.window.move({ into_group = "r" }), { description = "Move window right in group" })

hl.bind("SUPER + ALT + UP", hl.dsp.window.move({ into_group = "u" }), { description = "Move window up in group" })

hl.bind("SUPER + ALT + DOWN", hl.dsp.window.move({ into_group = "d" }), { description = "Move window down in group" })

-- Scroll grouped windows

hl.bind(
	"SUPER + ALT + mouse_down",
	hl.dsp.group.next(),
	{ mouse = true, description = "Focus next grouped window using mouse scroll" }
)

hl.bind(
	"SUPER + ALT + mouse_up",
	hl.dsp.group.next({ forward = false }),
	{ mouse = true, description = "Focus previous grouped window using mouse scroll" }
)

--
